# Paths to your MetaTrader 5 clients.
client = [
  'C:\local\mt5\mq\terminal64.exe',
  'C:\local\mt5\tt\terminal64.exe',
  'C:\your\mt5\terminal64.exe',
]

# Symbols for quick buttons.
symbol = [
  'EURUSD',
  'USDJPY',
]

# Main Window Size
# If the x value is 0, the window size will be decided automatically.
# [Windows] If you get the window scale setting 200%,
#           the window size will be twice as large as this settings.
[size]
x = 0
y = 0
